server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wms?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.200.151
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 4
logging:
  level:
    com.abc.backend_server.mapper : debug