
server:
  port: 8081
  # 安装包版本
  version: 1.0.4
  # 安装包名字
  upgrade-zip: upgrade.zip
spring:
  # 设置颜色
  output:
      ansi:
        enabled: ALWAYS
  # 应用名
  application:
    name: warehouse
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wms?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.200.130
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 3
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段


logging:
  level:
    com.abc.warehouse: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.abc.warehouse.pojo
